version: '3.8'
services:
  postgres-db:
    image: postgres:15
    container_name: workbridge-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: workbridge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workbridge-backend
    env_file:
      - .env
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workbridge-frontend
    ports:
      - "4200:4000"  # SSR Angular default port is 4000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge