services:
  workbridge-db:
    image: postgres:15
    container_name: workbridge-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: workbridge_db
    ports:
      - "5432:5432"
    volumes:
      - workbridge_data:/var/lib/postgresql/data
    networks:
      - shared-bridge
    restart: unless-stopped

  workbridge-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workbridge-backend
    env_file:
      - .env
    depends_on:
      - workbridge-db
    ports:
      - "8080:8080"
    networks:
      - shared-bridge
    restart: unless-stopped

  workbridge-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workbridge-frontend
    ports:
      - "4200:80"  # SSR Angular default port is 4000
    depends_on:
      - workbridge-backend
    networks:
      - shared-bridge

  minio:
    image: minio/minio
    container_name: workbridge-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"     # MinIO Web Console
      - "9001:9001"     # MinIO S3 API
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - shared-bridge
    restart: unless-stopped

volumes:
  workbridge_data:
  minio_data:

networks:
  shared-bridge:
