spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.connection.characterEncoding: UTF-8
      hibernate.connection.useUnicode: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  logging:
    level:
      root: WARN
      com.workbridge: INFO

security:
    public-urls:
      - /api/v1/auth/**
      - /api/v1/ws-chat
      - /api/v1/ws-chat/**
    cors:
      allowed-origins:
        - http://localhost:4200
        - http://frontend

auth:
  cookie:
    secure: true
