server:
  address: 0.0.0.0
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
    default: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

auth:
  refresh-token-validity-days: 7
